language: objective-c
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.0

before_install:
  - gem install cocoapods -v '1.2.0'
  - pod repo update

script:
    - xcodebuild clean build test -sdk iphonesimulator -workspace CodPol.xcworkspace -scheme CodPol CODE_SIGNING_REQUIRED=NO
